services:
  react:
    tty: true
    build:
      context: ./ClientApp
      dockerfile: Dockerfile
    ports: 
      - "3001:3000"
    environment: 
      - CHOKIDAR_USEPOLLING=true
  node:
    tty: true
    build:
      context: ./node
      dockerfile: Dockerfile
    ports: 
      - "5001:5000"
    