services:
  react:
    tty: true
    build:
      context: ./ClientApp
      dockerfile: Dockerfile
    ports: 
      - "3001:3000"
    environment: 
      - CHOKIDAR_USEPOLLING=true
  node:
    tty: true
    build:
      context: ./node
      dockerfile: Dockerfile
    restart: always
    ports: 
      - "8000:8080"
  mongo:
    container_name: mongodb
    image: mongo
    restart: always
    volumes:
      - ./mongoDb:/data/db
    ports:
      - "27017:27017"